name: Setup
description: Set up environment

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install Yarn
      run: |
        curl --compressed -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 3.3.0
      shell: bash

    - name: Set up PATH
      run: |
        echo "::set-env name=PATH::$HOME/.yarn/bin:$PATH"
      shell: bash

    - uses: actions/cache@v3
      id: cache
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}

