name: Setup
description: Set up environment

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install Yarn
      shell: bash
      run: corepack enable

    - uses: actions/cache@v3
      id: cache
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}

